name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    - name: Build 3rd data
      run: |
        python -m bdat 
    - name: Install dependencies
      run: |
        python -m pip install pyyaml
        python -m pip install coverage
    - name: Run tests and collect coverage
      run: |
        coverage run -m unittest discover
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
